@startuml apple_pay

!include ../skin.wsd

title Apple Pay

actor "Customer / SDK" as User
entity "Merchant Backend" as MEC
control "MobiLab Backend" as MBE
entity "Payment Provider (PSP)" as PSP

User -> MEC: Checkout { ApplePayToken, Data }
MEC -> MBE: Authorize { ApplePayToken, x€, "Reason", ... }
MBE -> PSP: Authorize { ApplePayToken, x€, "Reason" }
PSP -> MBE: { Status, PspTransactionId }
MBE -> MEC: { Status, TransactionId }
MEC -> User: { Status, TransactionId }

... 20 min later ...
MBE -> PSP: Capture { PspTransactionId }

@enduml