@startuml backend

!include ../skin.wsd

title Node thinking brainstorming

component AndroidSDK
component IosSDK
component Dashboard
component MerchantBackend

package User {
  component Login
  component DataInterface as UserApi
}

package BaseData {
  component DataInterface as BaseDateApi
}

package Transaction {
  component SdkInterface
  component Agregator
  component MerchantInterface
}

package Adapter {
  component BSOne
  component Paypal
  component Klarna
  component Stripe
}

SdkInterface -> Agregator
Agregator <- MerchantInterface

AndroidSDK .-> SdkInterface
IosSDK .-> SdkInterface

SdkInterface .-> Paypal
SdkInterface .-> BSOne
SdkInterface .-> Klarna
SdkInterface .-> Stripe

MerchantInterface .-> Paypal
MerchantInterface .-> BSOne
MerchantInterface .-> Klarna
MerchantInterface .-> Stripe

Dashboard .-> Login
Dashboard .-> UserApi
Dashboard .-> BaseDateApi
Dashboard .-> Agregator
Dashboard .-> MerchantInterface
MerchantBackend .-> Agregator
MerchantBackend .-> MerchantInterface

Login -[hidden]right- UserApi
@enduml