@startuml cc_payment_registered

!include ../skin.wsd

title CC Payment of registered User

actor "Customer / SDK" as User
entity "Merchant Backend" as MEC
control "MobiLab Backend" as MBE
entity "Payment Provider (PSP)" as PSP

User -> MEC: Checkout (Token)
MEC -> MBE: Auth(x€, "Reason", Token, PurchaseId)
MBE -> PSP: Auth(x€, "Reason", Token)
PSP -> MBE: Result
MBE -> MEC: Result + TransactionId
MEC -> User: Result

MBE -> PSP: Capture Payment (after 20 min)

@enduml