@startuml cc_payment_registered

!include ../skin.wsd

title CC Payment of registered User

actor "Customer / SDK" as User
entity "Merchant Backend" as MEC
control "MobiLab Backend" as MBE
entity "Payment Provider (PSP)" as PSP

User -> MEC: Checkout { AliasId }
MEC -> MBE: Authorize { AliasId, x€, Reason, IdempotentKey }
MBE -> PSP: Authorize { PspAlias, x€, Reason }
PSP -> MBE: { Status, PspTransactionId }
MBE -> MEC: { Status, TransactionId }
MEC -> User: { Status, TransactionId }

... 20 min later ...
MBE -> PSP: Capture { PspTransactionId }

@enduml