@startuml cc_registration

!include ../skin.wsd

title CC Registration

actor "Customer / SDK" as User
control "MobiLab Backend" as MBE
entity "Payment Provider (PSP)" as PSP

User -> MBE: Create Alias
MBE -> User: { AliasId, Url} 

User -> PSP: Register { CreditCard Data }
PSP -> User: PspAlias

User -> MBE: Update Alias { PspAlias, AliasId }
MBE -> User: { AliasId }

@enduml