@startuml cc_registration

!include ../skin.wsd

title CC Registration

actor "Customer / SDK" as User
control "MobiLab Backend" as MBE
entity "Payment Provider (PSP)" as PSP

User -> MBE: Prepare Registration
MBE -> User: URL 
User -> PSP: CC Data
PSP -> User: Alias

User -> MBE: Alias
MBE -> User: JWT (Wrapped Alias)

@enduml