@startuml cc_transaction

!include ../skin.wsd

title CC Transaction

actor "Customer / SDK" as User
entity "Merchant Backend" as MEC
control "MobiLab Backend" as MBE
entity "Payment Provider (PSP)" as PSP

User -> MBE: GetPSP(forCC, MerchantId)
MBE -> User: URL

User -> PSP: CC Data
PSP -> User: Alias

User -> MBE: Alias
MBE -> User: JWT (Wrapped Alias)

User -> MEC: Checkout (JWT)
MEC -> MBE: Auth(x€, "Reason", JWT, PurchaseId)
MBE -> PSP: Auth(x€, "Reason", Alias)
PSP -> MBE: Result
MBE -> MEC: Result + TransactionId
MEC -> User: Result

MBE -> PSP: Capture Payment (after 20 min)

@enduml