@startuml cc_transaction_3d

!include ../skin.wsd

title CC Transaction 3D Secure

actor "Customer / SDK" as User
entity "Merchant Backend" as MEC
control "MobiLab Backend" as MBE
entity "Payment Provider (PSP)" as PSP
entity "Bank" 

... Register ...
User -> MBE: Create Alias
MBE -> User: { AliasId, Url} 

User -> PSP: Register { CreditCard Data }
PSP -> User: PspAlias

User -> MBE: Update Alias { PspAlias, AliasId }
MBE -> User: { AliasId }

... Payment ...
User -> MEC: Checkout { AliasId }
MEC -> MBE: Authorize { AliasId, x€, Reason, IdempotentKey }
MBE -> PSP: Authorize { PspAlias, x€, Reason }
PSP -> Bank: Authorize { CCData, x€, Reason }
Bank -> PSP: { 3dSecureRequired, URL }
PSP -> MBE: { 3dSecureRequired, URL }
MBE -> MEC: { 3dSecureRequired, URL, TransactionId }
MEC -> User: { 3dSecureRequired, URL }
User -> Bank: 2 Factor Pin
Bank -> User: Ok
User -> MEC: ok?
Bank -> PSP: Confirm { 3dSecureOK, ... }
PSP -> MBE: Confirm { 3dSecureOK, PspTransaction }
MBE -> MEC: Confirm { 3dSecureOK, TransactionId }
MEC -> User: OK!

... 20 min later ...
MBE -> PSP: Capture { PspTransactionId }

@enduml