@startuml

skinparam handwritten true
skinparam sequenceMessageAlign center
skinparam ActorBackgroundColor #08E8DE
skinparam ActorBorderColor #035C58
skinparam ActorFontColor #172935
skinparam ActorFontName Raleway
skinparam ArrowColor #035C58
skinparam ArrowFontColor #172935
skinparam ArrowFontName Raleway
skinparam ControlBackgroundColor #08E8DE
skinparam ControlBorderColor #035C58
skinparam ControlFontColor #172935
skinparam ControlFontName Raleway
skinparam EntityBackgroundColor #08E8DE
skinparam EntityBorderColor #035C58
skinparam EntityFontColor #172935
skinparam EntityFontName Raleway
skinparam SequenceLifeLineBorderColor #035C58
skinparam SequenceTitleFontColor #172935
skinparam SequenceTitleFontName Raleway
skinparam SequenceTitleFontSize 25

title CC Transaction

actor "User / SDK" as User
entity "Merchant Backend" as MEC
control "MobiLab Backend" as MBE
entity "Payment Provider (PSP)" as PSP

User -> MBE: GetPSP(forCC, MerchantId)
MBE -> User: URL

User -> PSP: CC Data
PSP -> User: Token

User -> MEC: Checkout (Token)
MEC -> MBE: Auth(x€, "Reason", Token, PurchaseId)
MBE -> PSP: Auth(x€, "Reason", Token)
PSP -> MBE: Result
MBE -> MEC: Result + TransactionId
MEC -> User: Result

MBE -> PSP: Capture Payment (after 20 min)

@enduml