@startuml cc_transaction

!include ../skin.wsd

title CC Transaction

actor "Customer / SDK" as User
entity "Merchant Backend" as MEC
control "MobiLab Backend" as MBE
entity "Payment Provider (PSP)" as PSP

... Register ...
User -> MBE: Create Alias
MBE -> User: { AliasId, Url} 

User -> PSP: Register { CreditCard Data }
PSP -> User: PspAlias

User -> MBE: Update Alias { PspAlias, AliasId }
MBE -> User: { AliasId }

... Payment ...
User -> MEC: Checkout { AliasId }
MEC -> MBE: Authorize { AliasId, x€, Reason, IdempotentKey }
MBE -> PSP: Authorize { PspAlias, x€, Reason }
PSP -> MBE: { Status, PspTransactionId }
MBE -> MEC: { Status, TransactionId }
MEC -> User: { Status, TransactionId }

... 20 min later ...
MBE -> PSP: Capture { PspTransactionId }

@enduml