@startuml

skinparam handwritten true
skinparam ControlBorderColor #035C58
skinparam ControlBackgroundColor #08E8DE
skinparam sequenceMessageAlign center
skinparam EntityBackgroundColor #08E8DE
skinparam EntityBorderColor #035C58
skinparam ActorBackgroundColor #08E8DE
skinparam ActorBorderColor #035C58
skinparam ArrowColor #035C58
skinparam SequenceLifeLineBorderColor #035C58

title Chargeback CC Transaction

actor "User" as User
entity "Bank" as Bank
entity "Payment Provider (PSP)" as PSP
control "MobiLab Backend" as MBE
entity "Merchant Backend" as MEC

User -> Bank: Wants Chargeback
Bank -> PSP: Informs about Chargeback
PSP -> MBE: Informs about Chargeback
MBE -> MEC: Informs about Chargeback
MEC -> User: Deactivate Account

@enduml