@startuml

!include ../skin.wsd

title Chargeback CC Transaction

actor "User" as User
entity "Bank" as Bank
entity "Payment Provider (PSP)" as PSP
control "MobiLab Backend" as MBE
entity "Merchant Backend" as MEC

User -> Bank: Wants Chargeback
Bank -> PSP: Informs about Chargeback
PSP -> MBE: Informs about Chargeback
MBE -> MEC: Informs about Chargeback
MEC -> User: Deactivate Account

@enduml