@startuml delete_payment

!include ../skin.wsd

title Delete Payment Data

actor "Customer / SDK" as User
control "MobiLab Backend" as MBE
entity "Payment Provider (PSP)" as PSP
entity "Mechant Backend" as MEC

User -> MBE: Delete Payment (JWT)
MBE -> PSP: Delete Payment (Alias)
PSP -> MBE: OK
MBE -> User: OK
MBE -> MEC: Notifies about delete

@enduml