@startuml

!include ../skin.wsd

title Delete Payment Data

actor "User / SDK" as User
control "MobiLab Backend" as MBE
entity "Payment Provider (PSP)" as PSP
entity "Mechant Backend" as MEC

User -> MBE: PrepareDeletePayment(MerchantId)
MBE -> User: URL

User -> PSP: Delete Token
PSP -> User: OK
PSP -> MBE: Notifies
MBE -> MEC: Notifies

@enduml