@startuml erm

!include ../skin.wsd

title ERM

package BaseData {
    class psp << TABLE >>{
        id: string(3)
        --
        name: string(10)
    }

    class paymentmethode << TABLE >>{
        id: string(3)
        --
        name: string
    }

    class psp_paymentmethode << TABLE >>{
        psp_id: string(3)
        paymentmethode_id: string(3)
        --
    }

    class merchant << TABLE >>{
        id: int
        --
        name: string 
        email: string
        default_currency_id: string(3)
        created_at: Timestamp
        last_changed_at: Timestamp
        ...
    }

    class merchant_api_key << TABLE >>{
        mechant_id: int
        secret_key: string
        --
        is_active: bool
        keytype: string
        created_at: Timestamp
    }

    class merchant_psp << TABLE >>{
        mechant_id: int
        psp_id: string(3)
        --
        data: JSON
        created_at: Timestamp
        last_changed_at: Timestamp
    }

    class merchant_user << TABLE >>{
        id: int
        --
        username: string
        password: string
        merchant_id: string
        locale: string
        created_at: Timestamp
        last_changed_at: Timestamp
    }

    merchant_psp .> merchant
    psp <-. merchant_psp 
    merchant_api_key .-> merchant 
    merchant <. merchant_user 
    psp_paymentmethode .-> paymentmethode
    psp_paymentmethode .> psp
}

package TransactionData {
    class alias << TABLE >>{
        id: string
        --
        psp_alias: string
        extra: JSON
        merchant_id: int
        psp_id: string(3)
        paymentmethode_id: string(3)
        activat: bool
        created_at: Timestamp
        last_changed_at: Timestamp
    }

    class transaction_record << TABLE >>{
        id: int
        --
        transaction_id: string
        amount: decimal
        merchant_id: int
        reason: string
        alias_id: string
        type: AUTH,REVERSAL,REFUND,CAPTURE
        status: SUCESS,FAIL
        paymentmethode_id: string(3)
        merchant_transaction_id: string
        merchant_customer_id: string
        created_at: Timestamp
    }

    alias <. transaction_record
}

paymentmethode <.- alias
merchant <.- alias
paymentmethode <.- transaction_record
merchant <.- transaction_record

@enduml