@startuml erm

!include ../skin.wsd

title ERM

package BaseData {
    class psp << TABLE >>{
        id: string(3)
        --
        name: string(10)
        ...
    }

    class paymentmethode << TABLE >>{
        id: string(3)
        --
        name: string
        ...
    }

    class psp_paymentmethode << TABLE >>{
        psp_id: string(3)
        paymentmethode_id: string(3)
        --
        ...
    }

    class merchant << TABLE >>{
        id: int
        --
        name: string 
        email: string
        default_currency_id
        ...
    }

    class merchant_api_key << TABLE >>{
        mechant_id: int
        secret_key: string
        --
        is_active: bool
        keytype: string
    }

    class merchant_psp << TABLE >>{
        mechant_id: int
        psp_id: string
        --
        data: JSON
    }

    class merchant_user << TABLE >>{
        id: string
        --
        username: string
        password: string
        merchant_id: string
        locale: string
    }

    merchant <. merchant_api_key 
    merchant_psp .> merchant
    psp <. merchant_psp
    merchant <-. merchant_user
    psp_paymentmethode .-> paymentmethode
    psp_paymentmethode .> psp
}

package TransactionData {
    class alias << TABLE >>{
        id: int
        --
        psp_alias: string
        extra: JSON
        merchant_id: int
        paymentmethode_id: string(3)
    }

    class transaction_record << TABLE >>{
        id: int
        --
        transaction_id: int
        amount: decimal
        merchant_id: int
        reason: string
        alias_id: int
        type: AUTH,REVERSAL,REFUND,CAPTURE
        status: SUCESS,FAIL
        paymentmethode_id: string(3)
        merchant_transaction_id: string
        merchant_customer_id: string
    }

    alias <. transaction_record
}

paymentmethode <.- alias
paymentmethode <.- transaction_record

@enduml