@startuml klarna

!include ../skin.wsd

title Klarna

actor "Customer / SDK" as User
entity "Karna Sdk" as PAS
entity "Karna" as PAB
control "MobiLab Backend" as MBE
entity "Merchant Backend" as MEC

User -> MEC: GetAmount / perpare checkout
MEC -> User: Amount
User -> MBE: GetKlarnaConfirmUrl (Amount, MerchantId)
MBE -> User: Url
User -> PAS: ConfirmURL, Amount
PAS -> PAB: Authorize Amount
PAB -> MBE: Call ConfirmURL
MBE -> MEC: Confirm if all OK 
PAB -> PAS: Response
PAS -> User: Response
User -> MBE: All Ok?
MBE -> User: OK!

@enduml