@startuml klarna

!include ../skin.wsd

title Klarna

actor "Customer / SDK" as User
entity "Klarna SDK" as PAS
entity "Klarna" as PAB
control "MobiLab Backend" as MBE
entity "Merchant Backend" as MEC

User -> MBE: Create Alias { Cart }
MBE -> PAB: SetupPayment { Cart }
PAB -> MBE: { KlarnaPayToken }
MBE -> User: { KlarnaPayToken, AliasId, TransactionId }
User -> PAS: Init (KlarnaPayToken)
PAS -> PAB: Confirm { ... }
PAB -> PAS: { Status }
PAS -> User: { Status }
User -> MBE: FinishTransaction { AliasId, TransactionId }
MBE -> PAB: CheckTransaction { KlarnaPayToken }
PAB -> MBE: { Status }

MBE -> User: { Status }

... async ...
MBE -> MEC: Notify { TransactionId, PurchanseId } 
PAB -> MBE: Notify { KlarnaPayToken, ...}

@enduml
