@startuml

!include ./skin.wsd

title Paypal Transaction

actor "User / SDK" as User
entity "Paypal Sdk" as PAS
entity "Paypal" as PAB
control "MobiLab Backend" as MBE
entity "Merchant Backend" as MEC

User -> MEC: GetAmount / perpare checkout
MEC -> User: Amount
User -> MBE: GetPaypalConfirmUrl (Amount, MerchantId)
MBE -> User: Url
User -> PAS: ConfirmURL, Amount
PAS -> PAB: Authorize Amount
PAB -> MBE: Call ConfirmURL
MBE -> MEC: Confirm if all OK 
PAB -> PAS: Response
PAS -> User: Response
User -> MEC: All Ok?
MEC -> User: OK!
@enduml