@startuml paypal

!include ../skin.wsd

title Paypal Transaction

actor "Customer / SDK" as User
entity "Paypal SDK" as PAS
entity "Paypal" as PAB
control "MobiLab Backend" as MBE
entity "Merchant Backend" as MEC

User -> MBE: Prepare (Amount, MerchantId)
MBE -> User: Url + ...
User -> PAS: Init (ConfirmURL, Amount)
PAS -> PAB: Authorize Amount
PAB -> MBE: Call ConfirmURL
MBE -> MEC: Confirm if all OK 
PAB -> PAS: Response
PAS -> User: Response
User -> MBE: All Ok?
MBE -> User: OK!

@enduml
