@startuml

skinparam handwritten true
skinparam sequenceMessageAlign center
skinparam ActorBackgroundColor #08E8DE
skinparam ActorBorderColor #035C58
skinparam ActorFontColor #172935
skinparam ActorFontName Raleway
skinparam ArrowColor #035C58
skinparam ArrowFontColor #172935
skinparam ArrowFontName Raleway
skinparam BackgroundColor #F5FEFE
skinparam ControlBackgroundColor #08E8DE
skinparam ControlBorderColor #035C58
skinparam ControlFontColor #172935
skinparam ControlFontName Raleway
skinparam DiagramBorderColor #172935
skinparam DiagramBorderThickness 5
skinparam EntityBackgroundColor #08E8DE
skinparam EntityBorderColor #035C58
skinparam EntityFontColor #172935
skinparam EntityFontName Raleway
skinparam SequenceLifeLineBorderColor #035C58
skinparam SequenceTitleFontColor #172935
skinparam SequenceTitleFontName Raleway
skinparam SequenceTitleFontSize 25

title Paypal Transaction

actor "User / SDK" as User
entity "Paypal Sdk" as PAS
entity "Paypal" as PAB
control "MobiLab Backend" as MBE
entity "Merchant Backend" as MEC

User -> MEC: GetAmount / perpare checkout
MEC -> User: Amount
User -> MBE: GetPaypalConfirmUrl (Amount, MerchantId)
MBE -> User: Url
User -> PAS: ConfirmURL, Amount
PAS -> PAB: Authorize Amount
PAB -> MBE: Call ConfirmURL
MBE -> MEC: Confirm if all OK 
PAB -> PAS: Response
PAS -> User: Response
User -> MEC: All Ok?
MEC -> User: OK!
@enduml