@startuml refund_cc

!include ../skin.wsd

title Refund CC Transaction

actor "Customer" as User
actor "Merchant" as Merchant
control "MobiLab Backend" as MBE
entity "Payment Provider (PSP)" as PSP
entity "Merchant Backend" as MEC

User -> Merchant: Ask for Redund
Merchant -> MBE: Refund { transactionId, x€, reason }
MBE -> PSP: Refund { PspAlias, x€, reason }
PSP -> MBE: { Status PspTransaction }
MBE -> MEC: Notifies { PurchaseId, Transaction, ...}
MBE -> Merchant: { Status }
Merchant -> User: Confirms Refund

@enduml