@startuml

!include ../skin.wsd

title Report

actor "Merchant" as MEC
control "MobiLab Backend" as MBE

MEC -> MBE: Get Export (UI / API)
MBE -> MEC: Report (Excel, CSV, PDF)
MBE -> MEC: Daily / Weekly / Monthly Report (Mail, API Call)

@enduml