@startuml sepa_registration

!include ../skin.wsd

title Sepa Registration

actor "Customer / SDK" as User
control "MobiLab Backend" as MBE
entity "Payment Provider (PSP)" as PSP

User -> MBE: Create Alias
MBE -> User: { AliasId } 

User -> MBE: Update Alias { AliasId, IBAN, AccountData }

MBE -> PSP: Register { IBAN, AccountData }
PSP -> MBE: { Mandate }

MBE -> User: OK

@enduml