@startuml sepa_transaction

!include ../skin.wsd

title Sepa Transaction

actor "Customer / SDK" as User
entity "Merchant Backend" as MEC
control "MobiLab Backend" as MBE
entity "Payment Provider (PSP)" as PSP

User -> PSP: IBAN, and Account Data
PSP -> User: Alias

User -> MBE: Alias
MBE -> PSP: GetMandat
PSP -> MBE: Mandat
MBE -> User: JWT (Wrapped Alias, Mandat)

User -> MEC: Checkout (JWT)
MEC -> MBE: Auth(x€, "Reason", JWT, PurchaseId)
MBE -> PSP: Auth(x€, "Reason", Alias)
PSP -> MBE: Result
MBE -> MEC: Result + TransactionId
MEC -> User: Result

PSP -> MBE: Confirmation Payment (up to one 1 business day later)
MBE -> MEC: Confirmation Payment (PuchaseId, TransactionId)

@enduml