@startuml sepa_transaction_fail

!include ../skin.wsd

title Failed Sepa Transaction

actor "Customer / SDK" as User
entity "Merchant Backend" as MEC
control "MobiLab Backend" as MBE
entity "Payment Provider (PSP)" as PSP

... Register ...
User -> MBE: Create Alias
MBE -> User: { AliasId } 

User -> MBE: Update Alias { AliasId, IBAN, AccountData }

MBE -> PSP: Register { IBAN, AccountData }
PSP -> MBE: { Mandate }

MBE -> User: { AliasId, Mandat }

... Payment ...
User -> MEC: Checkout { AliasId }
MEC -> MBE: Authorize { AliasId, x€, Reason, IdempotentKey }
MBE -> PSP: Authorize { Mandate, IBAN, x€, Reason }
PSP -> MBE: { Status, PspTransactionId }
MBE -> MEC: { Status, TransactionId }
MEC -> User: { Status, TransactionId }

... up to one 1 business day later ...
PSP -> MBE: Notifies Confirmation failed { PspTransaction }
MBE -> MEC: Notifies Confirmation failed { PuchaseId, TransactionId }

... Possile Mechant action ...

MEC -> User: Email to User / Deactivate Account

@enduml