@startuml sepa_registration

!include ../skin.wsd

title Sepa Registration

actor "Customer / SDK" as User
control "MobiLab Backend" as MBE
entity "Payment Provider (PSP)" as PSP

User -> MBE: Create Alias
MBE -> User: { AliasId, Url} 

User -> PSP: Register { IBAN, AccountData }
PSP -> User: PspAlias

User -> MBE: Update Alias { PspAlias, AliasId, ibanMask }
MBE -> PSP: GetMandat { PspAlias }
PSP -> MBE: { Mandat }
MBE -> User: { AliasId, Mandat }

@enduml