@startuml sepa_registration

!include ../skin.wsd

title Sepa Registration

actor "Customer / SDK" as User
control "MobiLab Backend" as MBE
entity "Payment Provider (PSP)" as PSP

User -> MBE: GetPSP(forSepa, MerchantId)
MBE -> User: URL

User -> PSP: IBAN, and Account Data
PSP -> User: Token

@enduml