@startuml

skinparam handwritten true
skinparam ControlBorderColor #035C58
skinparam ControlBackgroundColor #08E8DE
skinparam sequenceMessageAlign center
skinparam EntityBackgroundColor #08E8DE
skinparam EntityBorderColor #035C58
skinparam DatabaseBackgroundColor #08E8DE
skinparam DatabaseBorderColor #035C58
skinparam ActorBackgroundColor #08E8DE
skinparam ActorBorderColor #035C58
skinparam ArrowColor #035C58
skinparam SequenceLifeLineBorderColor #035C58

title "Paypal Transaction"

actor "User / SDK" as User
entity "Paypal Sdk" as PAS
entity "Paypal" as PAB
control "MobiLab Backend" as MBE
entity "Merchant Backend" as MEC

User -> MEC: GetAmount / perpare checkout
MEC -> User: Amount
User -> MBE: GetPaypalConfirmUrl (Amount, MerchantId)
MBE -> User: Url
User -> PAS: ConfirmURL, Amount
PAS -> PAB: Authorize Amount
PAB -> MBE: Call ConfirmURL
MBE -> MEC: Confirm if all OK 
PAB -> PAS: Response
PAS -> User: Response
User -> MEC: All Ok?
MEC -> User: OK!
@enduml