@startuml

title "Refund CC Transaction"

actor "User" as User
actor "Mechant" as Mechant
control "Mobilab Backend" as MBE
entity "Payment Provider (PSP)" as PSP
entity "Mechant Backend" as MEC

User -> Mechant: Ask for Redund
Mechant -> MBE: Initiates Refund (transactionId)
MBE -> PSP: Process Refund (token, amount)
PSP -> MBE: Confirms Refund
MBE -> MEC: Notifies about Refund
MBE -> Mechant: Confirms Refund
Mechant -> User: Confirms Refund

@enduml