@startuml

title "Refund CC Transaction"

actor "User" as User
actor "Merchant" as Merchant
control "MobiLab Backend" as MBE
entity "Payment Provider (PSP)" as PSP
entity "Merchant Backend" as MEC

User -> Merchant: Ask for Redund
Merchant -> MBE: Initiates Refund (transactionId)
MBE -> PSP: Process Refund (token, amount)
PSP -> MBE: Confirms Refund
MBE -> MEC: Notifies about Refund
MBE -> Merchant: Confirms Refund
Merchant -> User: Confirms Refund

@enduml