@startuml skin

!define TABLE (T, #08E8DE)

skinparam handwritten true
skinparam sequenceMessageAlign center
skinparam ActorBackgroundColor #08E8DE
skinparam ActorBorderColor #035C58
skinparam ActorFontColor #172935
skinparam ActorFontName Raleway
skinparam ArrowColor #035C58
skinparam ArrowFontColor #172935
skinparam ArrowFontName Raleway
skinparam BackgroundColor #F5FEFE
skinparam ClassAttributeFontColor #172935
skinparam ClassAttributeFontName Raleway
skinparam ClassBackgroundColor #3AEDE5
skinparam ClassBorderColor #035C58
skinparam ClassFontColor #172935
skinparam ClassFontName Raleway
skinparam ClassHeaderBackgroundColor #9DF6F2
skinparam ComponentBackgroundColor #3AEDE5
skinparam ComponentBorderColor #035C58
skinparam ComponentFontColor #172935
skinparam ComponentFontName Raleway
skinparam ControlBackgroundColor #08E8DE
skinparam ControlBorderColor #035C58
skinparam ControlFontColor #172935
skinparam ControlFontName Raleway
skinparam DiagramBorderColor #172935
skinparam DiagramBorderThickness 5
skinparam EntityBackgroundColor #08E8DE
skinparam EntityBorderColor #035C58
skinparam EntityFontColor #172935
skinparam EntityFontName Raleway
skinparam PackageBackgroundColor #F5FEFE
skinparam PackageBorderColor #035C58
skinparam PackageFontColor #172935
skinparam PackageFontName Raleway
skinparam SequenceLifeLineBorderColor #035C58
skinparam SequenceTitleFontColor #172935
skinparam SequenceTitleFontName Raleway
skinparam SequenceTitleFontSize 25
skinparam TitleFontColor #172935
skinparam TitleFontName Raleway
skinparam TitleFontSize 25
@enduml
